% make_simple_waves

fs = 1e3;
dt = 1/fs;
N = 10001;
t = (0:N-1)*dt;

sin8Hz = dg_mkwave(struct( ...
    'form', 'sin', ...
    'param', 0, ...
    'freq', 8*ones(1,N), ...
    'amp', 1, ...
    'freqmod', [], ...
    'ampmod', [] ), fs);

cos8Hz = dg_mkwave(struct( ...
    'form', 'sin', ...
    'param', 0.25, ...
    'freq', 8*ones(1,N), ...
    'amp', 1, ...
    'freqmod', [], ...
    'ampmod', [] ), fs);

% Two frequency cross sweep with hanning envelope
cross_sweep = dg_mkwave(struct( ...
    'form', {'sin' 'sin'}, ...
    'param', 0, ...
    'freq', {(0:N-1)/10, (N-1:-1:0)/20 + 10}, ...
    'amp', {hanning(N), hanning(N)}, ...
    'freqmod', {[],[],},  ...
    'ampmod', {[],[],} ), fs);

% 1 Hz Square wave the hard, imperfect way
sqr = zeros(N,1);
for k = 1:100
    f = (1 + (k-1)*2);
    sqr = sqr + dg_mkwave(struct( ...
        'form', 'sin', ...
        'param', 0, ...
        'freq',  f * ones(1,N), ...
        'amp', 1/f, ...
        'freqmod', [], ...
        'ampmod', [] ), fs);
end

% 1 Hz rectangular wave with 70% duty cycle
rec70 = dg_mkwave(struct( ...
    'form', 'sqr', ...
    'param', 0.7, ...
    'freq', ones(1,N), ...
    'amp', 1, ...
    'freqmod', [], ...
    'ampmod', [] ), fs);

% Something vaguely reminiscent of an LFP: a slightly randomized theta
% oscillation which amplitude modulates an independently slightly
% randomized gamma oscillation.  Plot the components and the final result.
wavespec(1) = struct( ...
    'form', 'pink', ...
    'param', exp(-2*pi*0.1/fs), ...
    'freq', [], ...
    'amp', 1, ...
    'freqmod', [], ...
    'ampmod', [] );
wavespec(2) = struct( ...
    'form', 'sin', ...
    'param', 0, ...
    'freq', 8*ones(1,N), ...
    'amp', 1, ...
    'freqmod', [1 0.1], ...
    'ampmod', []);
wavespec(3) = struct( ...
    'form', 'pink', ...
    'param', exp(-2*pi*1/fs), ...
    'freq', [], ...
    'amp', 1, ...
    'freqmod', [], ...
    'ampmod', []);
wavespec(4) = struct( ...
    'form', 'sin', ...
    'param', 0, ...
    'freq', 50*ones(1,N), ...
    'amp', 0.1, ...
    'freqmod', [3 0.5], ...
    'ampmod', [2 0.08]);
[wave, subwaves] = dg_mkwave(wavespec, fs);
finalmix = sum(subwaves(:, [2 4]), 2);
figure; plot_imf(subwaves',t,'subwaves');
figure; plot(t, finalmix)

% fcutoff = 0.2:0.4:2;
% for f = 1:length(fcutoff)
%    
%     wavespec(f) = struct( ...
%     'form', 'pink', ...
%     'param', exp(-2*pi*fcutoff(f)/fs), ...
%     'freq', [], ...
%     'amp', 1, ...
%     'freqmod', [], ...
%     'ampmod', []);
%     
% end
% [wave,subwaves] = dg_mkwave(wavespec, fs);
% figure; plot_imf(subwaves',t,'subwaves')

