function [mixedwave, subwaves] = make_bursts(f1, f2, a2)
% Creates a 10 s long series of 2/s bursts sampled at 1000 Hz, comprising
% one burst train at N + 0.2 s and N + 0.6 s ("earlier"), where N is 0:9,
% and another at N + 0.2 s and N + 0.7 s ("later').  The duration of each
% burst is 0.25 s.  The carrier frequency of the earlier burst train is
% modulated by a pink noise source with a low cutoff of 1 Hz to produce
% random phase relations between successive pairs of bursts.
%INPUTS
% f1: frequency of earlier burst
% f2: frequency of later burst
% a2: amplitude of later burst relative to earlier burst
%OUTPUTS
% mixedwave: ya know
% subwaves: the components that are summed to create <mixedwave>, in waves
%   X samples format

numsamp = 10001;
Fs = 1000;

burst1TS = zeros(numsamp, 1);
burst1TS(200:1000:end) = 1;
burst1TS(600:1000:end) = 1;
burst2TS = zeros(numsamp, 1);
burst2TS(200:1000:end) = 1;
burst2TS(700:1000:end) = 1;
burst1env = conv(burst1TS, hanning(250), 'same');
burst2env = a2 * conv(burst2TS, hanning(250), 'same');

wavespec(1) = struct( 'form', 'pink', ...
    'param', exp(-2*pi*1/Fs), ...
    'freq', 1, ...
    'amp', 1, ...
    'freqmod', [], ...
    'ampmod', [] );
wavespec(2) = struct( 'form', 'sin', ...
    'param', 0, ...
    'freq', f1*ones(1,numsamp), ...
    'amp', burst1env, ...
    'freqmod', [1 f1/100], ...
    'ampmod', [] );
wavespec(3) = struct( 'form', 'pink', ...
    'param', exp(-2*pi*5/Fs), ...
    'freq', 1, ...
    'amp', 0.05, ...
    'freqmod', [1 0.5], ...
    'ampmod', [] );
wavespec(4) = struct( 'form', 'sin', ...
    'param', 0, ...
    'freq', f2*ones(1,numsamp), ...
    'amp', burst2env, ...
    'freqmod', [], ...
    'ampmod', [] );
[~, subwaves] = dg_mkwave(wavespec, Fs);
subwaves = subwaves(:, 2:4)';
mixedwave = sum(subwaves, 1);

